// Articles: longer reads about Iranian people and ideas.
// Where a piece draws on someone else's reporting, the source is credited
// and links out. Clean, book-like reading surface, minimal colour.

export const ar = {
  bg: '#FBF9F4',
  ink: '#221E1A',
  soft: '#6E655C',
  faint: '#A79E93',
  hair: '#E6DFD3',
  rule: '#CDbfa8',
  accent: '#8C6A3F',
};

export type ArBlock =
  | { t: 'lead'; x: string }
  | { t: 'p'; x: string }
  | { t: 'h'; x: string }
  | { t: 'quote'; x: string; who?: string }
  | { t: 'img'; key: string; cap?: string }
  | { t: 'pull'; x: string }
  | { t: 'line'; x: string }
  | { t: 'divider' };

export type Source = { label: string; url: string };

export type Article = {
  key: string;
  kicker: string;          // small line above the title
  title: string;
  standfirst: string;      // the deck under the title
  excerpt?: string;        // short catchy line for the cards
  author?: string;         // who wrote it for ZAND, if original
  readMins: number;
  cover: string;
  hero?: string;           // optional portrait inside
  tag: 'ARCHITECTURE' | 'ART' | 'SCIENCE' | 'PROFILE' | 'ESSAY';
  blocks: ArBlock[];
  source?: Source;         // faded credit at the foot, links out
};


const _ebi_obj: Article = {
  key: 'ebi',
  subject: 'Ebi',
  kicker: 'MUSIC',
  title: 'Fifty Years of a Voice Iran Was Told Not to Hear',
  standfirst: 'Ebrahim Hamedi left for a tour in 1977 and never came home. The ban that followed did not shrink his audience. It multiplied it.',
  excerpt: 'He left for a tour in 1977 and never came home. The ban that followed did not shrink his audience.',
  readMins: 7,
  cover: 'article-ebi-cover',
  hero: 'article-ebi-hero',
  tag: 'PROFILE',
  blocks: [
    { t: 'lead', x: 'Before he was a pop singer he was a boy reciting the Quran. He has said that is where the singing started, and it shows in the technique: breath held long, a note sustained without strain, meaning carried by weight rather than volume.' },
    { t: 'p', x: 'Ebrahim Hamedi was born in 1949, the eldest of six. His father came from Arak, his mother from Karaj. He sang at home, he sang to schoolmates, he sang to the children on his street. None of it was a career yet. It was a habit that happened to be a gift.' },
    { t: 'p', x: 'Then the Beatles reached Tehran. In the mid-sixties he formed a beat band called The Rebels with Shahram Shabpareh and Siavash Ghomayshi. He passed through the Sunboys and the Black Cats. By the early seventies he had stopped being one voice among several and started being the one people came for.' },
    { t: 'img', key: 'article-ebi-rebels' },
    { t: 'divider' },
    { t: 'h', x: 'The tour that never ended' },
    { t: 'p', x: 'In 1977 he flew to the United States to tour. Two years later the revolution came, and he did not go back. It is worth being precise about the sequence: he did not flee. He left for work, and the country he left stopped existing while he was away.' },
    { t: 'line', x: 'He packed for a tour. He has been on it for almost fifty years.' },
    { t: 'p', x: 'What happened next is the part that makes his career strange. His music was banned in Iran. Playing it was illegal. And the audience inside the country grew anyway, passed hand to hand on cassettes, then satellite, then the internet, until three generations knew the same songs by heart without ever having heard them on a radio at home.' },
    { t: 'pull', x: 'The ban did not remove him from Iranian life. It moved him underground, where he became something closer to a shared inheritance.' },
    { t: 'divider' },
    { t: 'h', x: 'The records that stuck' },
    { t: 'p', x: 'In 1990 he and Dariush released Noon O Panir O Sabzi together and played the Universal Amphitheatre. The same period gave him Khalij, built around a song about the Persian Gulf written by Adel Hassani and composed by Mohammad Shams. He has said it is one of the few of his own performances he is proud of.' },
    { t: 'p', x: 'The 1995 album Setarehaye Sorbi is the one that settled the argument. Iraj Janatie Ataie wrote the words, Siavash Ghomayshi wrote the music. When Manoto later ran a viewer poll for his twenty best songs, the top two places both came from that record.' },
    { t: 'img', key: 'article-ebi-stage' },
    { t: 'divider' },
    { t: 'h', x: 'Singing at the state' },
    { t: 'p', x: 'He has never treated the politics as separate from the work. Hala, released in 1999, set words by the poet Mina Assadi to a production by Esfandiar Monfaredzadeh; he has called it his most important political song. In 2009 he answered the disputed presidential election with Tasmim. In 2019, Koocheye Nastaran took on the Iran and Iraq war and the young men it consumed, and it drew exactly the argument you would expect.' },
    { t: 'p', x: 'In 2022 he stood outside the United Nations to protest Ebrahim Raisi’s appearance there, and backed the protests that followed Mahsa Amini’s death. His own framing is simple and he has repeated it for decades.' },
    { t: 'quote', x: 'I have always sung for my roots.', who: 'Ebi' },
    { t: 'divider' },
    { t: 'h', x: 'Still working' },
    { t: 'p', x: 'In 2014 he recorded Nostalgia with Googoosh and took it on tour, opening in Dubai. Two exiled voices from the same lost broadcast era, on the same stage, singing to rooms full of people who had grown up on both. It is difficult to think of a neater summary of what Iranian pop became after 1979.' },
    { t: 'p', x: 'The numbers are large and not really the point: more than thirty albums, close to two hundred singles, sold-out nights at the Royal Albert Hall, Wembley, the Sydney Opera House. He has three daughters from a first marriage that lasted twenty-five years, lived in Sweden in the early 2000s, and now divides his time between Marbella and Los Angeles.' },
    { t: 'line', x: 'The country that banned him has never stopped listening to him.' },
  ],
  source: {
    label: 'Drawn from interviews with Radio Zamaneh, BBC Persian and Manoto. Read more',
    url: 'https://en.wikipedia.org/wiki/Ebi',
  },
};


const _omid_obj: Article = {
  key: 'omid',
  subject: 'Omid Mouazzen',
  kicker: 'BUSINESS',
  title: 'Omid Mouazzen Turned His Showroom Into an Audience',
  standfirst: 'He was already selling hypercars when he started filming them. The camera did not advertise the business. It became the business.',
  excerpt: 'He was already selling hypercars when he started filming them. The camera became the business.',
  readMins: 5,
  cover: 'article-omid-cover',
  hero: 'article-omid-hero',
  tag: 'PROFILE',
  blocks: [
    { t: 'lead', x: 'Most car dealers who build an audience do it the hard way round: get famous, then sell cars to the people watching. Omid Mouazzen did the opposite. He had the inventory first, and realised the inventory was the show.' },
    { t: 'p', x: 'He was born in Tehran in 1986 and came to Germany as a child. He took a finance degree at Ludwigshafen University of Applied Sciences in 2011 and a master’s in innovation management and finance there in 2014. The early years of the car business were unglamorous enough that the origin story is usually told as selling out of a parking garage, with a childhood friend.' },
    { t: 'p', x: 'Automobilzentrum Rhein-Neckar was registered in Viernheim in December 2016. The premise was narrow on purpose: not used cars generally, but the top of the market. Ferrari, Lamborghini, Bugatti, Rolls-Royce, and the tuned variants that sit above them.' },
    { t: 'img', key: 'article-omid-showroom' },
    { t: 'divider' },
    { t: 'h', x: 'The thing he understood early' },
    { t: 'p', x: 'The channel launched in May 2023 under the name Hypercars and Lifestyle. It reached roughly 660,000 subscribers and over 570 million views by the middle of 2025, and around 800,000 by January 2026. That is fast, and the reason it was fast is worth stating plainly.' },
    { t: 'line', x: 'He was not producing content about cars. He was filming a job he was already doing.' },
    { t: 'p', x: 'A dealership at that level has permanent access to objects almost nobody gets to stand next to. Every arrival, every inspection, every negotiation is footage that costs nothing extra to capture. Other creators have to borrow a hypercar for a day. He walks past a hundred of them on the way to his desk.' },
    { t: 'pull', x: 'The inventory was the production budget. That is the whole trick, and it is not one most people can copy.' },
    { t: 'p', x: 'The loop then closes: the videos bring in buyers who would never have found a showroom in a town of 35,000 people, and those buyers generate the next videos. In 2025 a Dubai chief executive walked in and left having bought three cars, a Ford GT Heritage Edition, a Ferrari Purosangue and a Rolls-Royce Cullinan Black Badge, for over a million dollars in a single visit.' },
    { t: 'divider' },
    { t: 'h', x: 'The deals people remember' },
    { t: 'p', x: 'A Koenigsegg Jesko, sixteen hundred horsepower and around five million euros, sold to a client in Dubai in 2025 and flown out by air freight. A Rolls-Royce Dawn to the German rapper Apache 207, which then turned up in one of his music videos. The company was restructured into a GmbH in December 2022, with Mouazzen and Kivork Kazanjian as managing directors.' },
    { t: 'p', x: 'Not all of the attention has been flattering. In October 2025 he tried to mediate a public dispute over a Mercedes G-Class modified to look like a Brabus without certification, filmed both sides, was accused of taking one, and deleted the video. It resolved nothing and everyone involved got more attention out of it.' },
    { t: 'divider' },
    { t: 'h', x: 'Away from the showroom' },
    { t: 'p', x: 'He got a pilot’s licence and bought a Tecnam P2010 Grand Lusso for around 700,000 euros, registered D-EAOM, the last two letters his initials. He flew it home himself from Capua in Italy to Mannheim in August 2023, over the Alps, with a stop near Bologna. In 2023 he ran the Gumball 3000 in a Bugatti Chiron and hit a ladder lying on the Autobahn, which is how a good deal of the world first heard his name.' },
    { t: 'p', x: 'His own advice, given at industry conferences and in interviews, is consistent and unromantic: partnerships matter more than starting capital, and mistakes are the cheapest information available. In 2025 the German public broadcaster hr profiled him for the documentary series Auftrag Luxus, which framed the whole thing the way it usually gets framed, as a boy who arrived from Iran with nothing in particular and ended up selling five-million-euro cars to sheikhs.' },
    { t: 'img', key: 'article-omid-plane' },
  ],
  source: {
    label: 'Drawn in part from public reporting and the hr documentary Auftrag Luxus. Read more',
    url: 'https://grokipedia.com/page/Omid_Mouazzen',
  },
};

export const ARTICLES: Article[] = [
  {
    key: 'khalili',
    subject: 'Nader Khalili',
    kicker: 'ARCHITECTURE  ·  A LIFE',
    title: 'The Iranian Architect Already Building for Mars',
    standfirst: 'Nader Khalili believed the future of building was hidden in its oldest ideas: earth, geometry, and a pair of hands. NASA agreed.',
    excerpt: 'Six generations of beekeeping, a family honey recipe, and one of beauty’s fastest rises.',
    readMins: 4,
    cover: 'article-khalili-cover',
    hero: 'article-khalili-face',
    tag: 'ARCHITECTURE',
    blocks: [
      { t: 'lead', x: 'Nader Khalili spent his life chasing one stubborn idea: that the architecture of the future was already here, buried in the oldest traditions humanity has.' },
      { t: 'p', x: 'He was born in Iran in 1936 and later became an American architect, and somewhere between those two facts he arrived at a conviction that would carry him from the deserts of the Middle East to the planning rooms of NASA. The way forward, he believed, was not more. It was less.' },
      { t: 'p', x: 'Looking at the earthen buildings of his own part of the world, the mud domes and vaults that had sheltered people for thousands of years, Khalili stripped construction back to the few things it truly needs. Earth. Geometry. Human hands. Everything else, he came to think, was decoration on top of those three.' },
      { t: 'line', x: 'He reduced building to earth, geometry, and a pair of hands, and then asked what more you could possibly need.' },
      { t: 'divider' },
      { t: 'h', x: 'A method the space agencies noticed' },
      { t: 'p', x: 'That radical return to first principles is exactly what caught the attention of NASA. If a shelter could be built from little more than the soil beneath it, arranged by geometry understood for millennia, then the same logic might work somewhere with no supply chain at all. On the Moon. On Mars. Places where the only material worth counting on is the ground you land on.' },
      { t: 'pull', x: 'A house you can build from the dirt under your feet is exactly the house you would need on another planet.' },
      { t: 'p', x: 'Khalili called his system SuperAdobe: long tubes packed with earth, coiled into domes, bound with a little barbed wire, raised by hand. No heavy machinery. No imported steel. A structure that grows out of its own site and, crucially, that ordinary people can build themselves, without a factory or a crane.' },
      { t: 'img', key: 'article-khalili-face' },
      { t: 'divider' },
      { t: 'h', x: 'From the Omani desert to a California dome' },
      { t: 'p', x: 'The idea reads most beautifully in the built work. At the Junoot Eco Resort in Oman, SuperAdobe domes rise from the desert as though the landscape had simply decided to stand up. They do not sit on the land so much as continue it.' },
      { t: 'p', x: 'The method was developed and tested at Cal-Earth, the institute Khalili founded in Hesperia, California. Its Eco Dome is the idea in its quietest form: beneath a single earthen shell, light and simplicity produce a calm that is hard to describe and harder to forget. It is proof that the most elemental materials can make architecture of real dignity.' },
      { t: 'line', x: 'The oldest way of building turned out to be the one most ready for the future.' },
      { t: 'divider' },
      { t: 'h', x: 'Why it matters now' },
      { t: 'p', x: 'Cal-Earth still teaches the system as a way to put shelter within reach of communities across the world. And at a moment when millions face climate disaster, displacement, and the slow disappearance of cheap materials, Khalili’s vision has stopped feeling like nostalgia and started feeling like a plan.' },
      { t: 'p', x: 'That is his real legacy, and it is a profoundly human one. Not a signature building with his name on it. A belief: that the architecture of tomorrow can grow from the simplest ideas, and that it can belong to everyone, not only those who can afford steel and glass.' },
    ],
    source: {
      label: 'Drawn in part from “The Adventures of Super Adobe” on Bidoun. Read the original',
      url: 'https://www.bidoun.org/articles/the-adventures-of-super-adobe',
    },
  },
  {
    key: 'rassi',
    subject: 'Mazdack Rassi',
    kicker: 'BEAUTY',
    title: 'Mazdack Rassi Turned a Studio Into a Beauty Brand',
    standfirst: 'Mazdack Rassi built Milk Studios into a creative hub, then turned its culture into Milk Makeup, one of the defining clean beauty brands of the last decade.',
    excerpt: 'He ran the studio where the shoots happened, then built a beauty brand out of its culture.',
    readMins: 4,
    cover: 'article-rassi-cover',
    hero: 'article-rassi-hero',
    tag: 'PROFILE',
    blocks: [
      { t: 'lead', x: 'Before Milk Makeup existed, there was Milk Studios: the room where the shoots happened, the campaigns were made, and a large part of fashion and beauty simply passed through.' },
      { t: 'p', x: 'Mazdack Rassi co-founded Milk Studios in New York in 1998 and built it into one of the most influential creative spaces in the industry. It was a studio, a production company, and a gathering point all at once, the place photographers, editors, models, and brands came to make their best work. His vantage point was unusual. He was not on the outside trying to break into the culture. He was hosting it.' },
      { t: 'line', x: 'He did not study the creative world from a distance. He ran the room where it happened.' },
      { t: 'p', x: 'That matters, because it is the whole reason for everything that came next. Rassi spent years watching, up close, how images were made and how taste actually moved. He saw which ideas caught and which fell flat, not in theory but in the room, on the day, with the people who set the trends. Few people in beauty have ever had that view.' },
      { t: 'img', key: 'article-rassi-1' },
      { t: 'divider' },
      { t: 'h', x: 'Turning a culture into a product' },
      { t: 'p', x: 'Milk Makeup, launched in 2015, grew directly out of that studio and its ethos: fast, expressive, low-fuss, made for people who did their own makeup in the back of a cab between one thing and the next. It was clean before clean beauty was a category, and built for a generation that valued ease and self-expression over polish.' },
      { t: 'pull', x: 'A brand born inside a working studio carries a credibility a brand designed in a boardroom cannot fake.' },
      { t: 'p', x: 'That is the insight the whole company rests on. Milk Makeup did not have to invent a relationship with the creative community and hope people believed it. The relationship already existed. The brand came out of the exact place the culture was being made, and everyone in that world knew it.' },
      { t: 'img', key: 'article-rassi-2' },
      { t: 'divider' },
      { t: 'h', x: 'Ten years in' },
      { t: 'p', x: 'A decade later, Milk Makeup is an established name in a crowded field, and Rassi has spoken about how the brand’s commitment to creativity still feels fresh to him. That staying power comes from the same place the brand did: a real community, a clear point of view, and a founder who understood culture because he had been running the room where it lived.' },
      { t: 'line', x: 'He built the infrastructure of an industry first, then built a product on top of his own understanding of it.' },
      { t: 'p', x: 'It is a rare sequence, and the order is the entire story. Most founders study a market from the outside and guess. Rassi helped build the place the market was made, and only then made something to sell inside it. He had the map because he had drawn it.' }, ebi, omid],
    source: {
      label: 'Drawn in part from WWD\u2019s profile of Mazdack Rassi. Read the original',
      url: 'https://wwd.com/beauty-industry-news/beauty-features/feature/mazdack-rassi-milk-studios-beauty-community-1202679311/',
    },
  },
  {
    key: 'zadeh',
    subject: 'Sheena Zadeh',
    kicker: 'BEAUTY',
    title: 'Sheena Zadeh Made Makeup Behave Like Skincare',
    standfirst: 'Sheena Zadeh trained in cosmetic chemistry, then founded Kosas on a simple idea: makeup that is good for your skin and easy enough to actually wear.',
    excerpt: 'A cosmetic chemist who built Kosas on makeup that behaves like skincare, and wears like nothing.',
    readMins: 4,
    cover: 'article-zadeh-cover',
    hero: 'article-zadeh-hero',
    tag: 'PROFILE',
    blocks: [
      { t: 'lead', x: 'Sheena Zadeh came to beauty the technical way, through chemistry, and that single fact explains why Kosas works the way it does.' },
      { t: 'p', x: 'She trained in cosmetic chemistry. That means she understood formulation from the inside, not as a story to tell customers but as the actual substance of the thing. When most people start a beauty brand, they commission a product from someone else. Zadeh could build one herself, and knew exactly why each ingredient was there.' },
      { t: 'line', x: 'Most founders have to trust a lab. She was the lab.' },
      { t: 'p', x: 'The premise of Kosas was specific and, at the time, almost contrarian: makeup that is genuinely good for your skin, and comfortable enough that you forget you are wearing it. Not coverage that sits on the face like a mask, but color that behaves like skincare underneath it.' },
      { t: 'divider' },
      { t: 'h', x: 'The moment the line blurred' },
      { t: 'p', x: 'That premise landed at the exact moment the wall between skincare and makeup was coming down. People had stopped wanting heavy foundation and started wanting products that treated the skin while they wore them. Kosas was built for that shift before it had fully arrived, which is the hardest kind of timing to get right.' },
      { t: 'pull', x: 'She was not chasing the trend toward skin-first beauty. She had already formulated for it.' },
      { t: 'p', x: 'Foundations with active ingredients. Formulas that feel like nothing. Color that reads as better skin rather than a layer over it. Because Zadeh could actually formulate, the brand delivered on the promise instead of merely making it, and customers felt the difference the first time they used it. That is the gap between a claim and a product that keeps them coming back.' },
      { t: 'divider' },
      { t: 'h', x: 'Expertise as the moat' },
      { t: 'p', x: 'In an industry crowded with invented origin stories and borrowed credibility, Kosas had something much harder to copy: a founder who knew, at a molecular level, what she was making. That is not a marketing angle. It is a genuine advantage, and it compounds, because every new product starts from real understanding rather than a brief handed to a stranger.' },
      { t: 'quote', x: 'I wanted to make the things I actually wanted to wear, and I had the training to make them right.', who: 'Sheena Zadeh' },
      { t: 'p', x: 'Kosas grew into one of the defining names in clean, skin-first beauty, the kind of brand that sets the direction of a category rather than following it. The reason is not a slogan on the box. It is that the person who built it had the science to stand behind every claim on the label.' },
      { t: 'line', x: 'In a business full of stories, she had the chemistry.' },
    ],
    source: {
      label: 'Drawn in part from ELLE\u2019s interview with Sheena Zadeh. Read the original',
      url: 'https://www.elle.com/beauty/makeup-skin-care/a64920673/sheena-zadeh-kosas-career-interview/',
    },
  },
  {
    key: 'googoosh',
    subject: 'Googoosh',
    kicker: 'MUSIC  ·  AN ICON',
    title: 'The Voice They Tried to Silence for Twenty Years',
    standfirst: 'Googoosh was the biggest star in Iran. Then the revolution came, and for more than two decades she was not allowed to sing. When she finally sang again, the world was waiting.',
    excerpt: 'The biggest star in Iran, silenced for over twenty years. When she sang again, the world was waiting.',
    readMins: 5,
    cover: 'article-googoosh-cover',
    hero: 'article-googoosh-hero',
    tag: 'PROFILE',
    blocks: [
      { t: 'lead', x: 'Ask anyone who grew up in Iran in the 1970s to name the sound of that decade, and you will hear one name. Googoosh.' },
      { t: 'p', x: 'She barely had a childhood, at least not the ordinary kind. Her father was an entertainer, a struggling one, and he put his daughter to work almost as soon as she could stand in front of a crowd. She was performing before she was in school: a tiny girl on stages meant for grown men, learning to hold a room before she could fully read.' },
      { t: 'quote', x: 'I never chose the stage. The stage was simply where my father took me, and so it became the only home I knew.', who: 'Googoosh' },
      { t: 'p', x: 'That is the origin most people forget. Before Googoosh was glamour and fame, she was a working child, carried from town to town, singing for money her family needed. The confidence that would later define her was not a gift handed to a star. It was built, night after night, out of necessity, on stages where a child had to earn the attention of adults or go home with nothing.' },
      { t: 'img', key: 'article-googoosh-teen' },
      { t: 'p', x: 'By her teens the child performer had become something else. The voice deepened. The awkwardness turned into presence. Audiences that had once found her a novelty began to find her unforgettable, and the girl who had been pushed onto stages started to command them.' },
      { t: 'line', x: 'She had been performing her whole life. Now, for the first time, the whole country was watching.' },
      { t: 'p', x: 'By her twenties she was not simply famous. She was the mirror Iran held up to itself. Her haircuts became the haircut. Her clothes set the fashion. Her films filled the cinemas, and her songs poured out of every radio and taxi and open window.' },
      { t: 'quote', x: 'When I sang, I was not performing for them. I was telling them what they already felt but could not say.', who: 'Googoosh' },
      { t: 'p', x: 'To be a young Iranian woman in that era was, in some quiet way, to measure yourself against Googoosh. She was modern, glamorous, and completely her own, at the exact moment Iran was reaching for all three. She performed for the country’s elite and for the Shah himself, in the gilded final years of an era nobody knew was ending.' },
      { t: 'img', key: 'article-googoosh-stage' },
      { t: 'divider' },
      { t: 'h', x: 'And then the music stopped' },
      { t: 'p', x: 'The 1979 revolution did not send Googoosh into exile. That is the part people outside Iran often miss, and it is the part that matters most. Under the new order, women were forbidden to sing solo in public. And Googoosh, the most recognisable voice in the entire country, was inside its borders when the door closed.' },
      { t: 'pull', x: 'The most famous voice in Iran fell silent inside its own country, and stayed silent for over twenty years.' },
      { t: 'p', x: 'She did not leave. For more than two decades she lived in Tehran as a legend who was no longer allowed to be one. There were detentions. There was fear. There was the strange, suffocating experience of being known by everyone and heard by no one. A whole generation grew up hearing about Googoosh from their parents, playing old cassettes passed hand to hand, knowing the voice only as something from before.' },
      { t: 'line', x: 'She was present and absent at once: a silence with a name everyone knew.' },
      { t: 'divider' },
      { t: 'h', x: 'The voice comes back' },
      { t: 'p', x: 'In 2000, after more than twenty years, Googoosh was finally able to leave Iran. The first thing she did was the one thing she had been forbidden to do. She sang. The comeback was not a concert. It was an event, treated by Iranians everywhere as the recovery of something that had been taken from all of them. The voice was older now, and it carried every one of those silent years inside it.' },
      { t: 'divider' },
      { t: 'h', x: 'More than a singer' },
      { t: 'p', x: 'When a new generation of Iranian women rose up over their right to choose how they live, she stood with them, openly, using the fame that had survived everything. A woman silenced for twenty years became, in her seventies, a symbol of the refusal to be silenced at all.' },
      { t: 'line', x: 'They took her voice for twenty years. They never got it back.' },
      { t: 'p', x: 'Her life reads like the recent history of Iran pressed into a single person: the glamour, the rupture, the long forced quiet, and the voice that in the end would not stay down. That is why, for millions, she is not simply a singer they love. She is proof of something they need to believe.' },
    ],
    source: {
      label: 'Drawn in part from IranWire\u2019s profile of Googoosh. Read the original',
      url: 'https://iranwire.com/en/women/120759-iranian-influential-women-googoosh-1950-present/',
    },
  },
  {
    key: 'panahi',
    subject: 'Jafar Panahi',
    kicker: 'FILM',
    title: 'Jafar Panahi Kept Filming After They Banned Him',
    standfirst: 'Jafar Panahi was banned from making films for twenty years. He made some of his most celebrated work anyway, in secret, and kept winning the world\u2019s top festivals.',
    excerpt: 'Banned from filmmaking for twenty years, he kept making films in secret, and kept winning.',
    readMins: 3,
    cover: 'article-panahi-cover',
    hero: 'article-panahi-hero',
    tag: 'PROFILE',
    blocks: [
      { t: 'lead', x: 'In 2010, an Iranian court handed the filmmaker Jafar Panahi a sentence that would have ended most careers: twenty years without making films, writing scripts, giving interviews, or leaving the country. He has made some of his most admired work since.' },
      { t: 'p', x: 'Panahi is one of the most respected filmmakers alive, a central figure of Iranian cinema whose films are spare, humane, and quietly political. That last quality is what put him in the state’s path. His work kept looking, plainly and without permission, at the lives of ordinary Iranians, and that looking was treated as a threat.' },
      { t: 'divider' },
      { t: 'h', x: 'Making the films you are forbidden to make' },
      { t: 'p', x: 'Most people, told they may not work for twenty years, would stop. Panahi did the opposite, and turned the ban itself into the material. His first film under it was titled, with quiet defiance, This Is Not a Film. He shot it inside his own apartment while under house arrest, much of it on a phone, and had it smuggled out of the country to the Cannes festival on a drive hidden inside a cake.' },
      { t: 'pull', x: 'Told he could not make films, he made a film about not being allowed to make films, and sent it to Cannes inside a cake.' },
      { t: 'p', x: 'He kept going. He made a film almost entirely inside a moving car. He made others in secret, under conditions that would stop most productions before they began. Denied crews, locations, and permits, he built cinema out of small rooms and long conversations, and turned every limitation into a style.' },
      { t: 'line', x: 'The ban was meant to end his work. It became his subject instead.' },
      { t: 'divider' },
      { t: 'h', x: 'The world refused to look away' },
      { t: 'p', x: 'The international film community would not let him disappear. His films kept arriving at the major festivals, and kept winning their highest honours, at Cannes, at Venice, at Berlin. Each award was two things at once: recognition of the art, and a refusal to accept the silencing of the artist.' },
      { t: 'p', x: 'The prizes were not sentiment. The films earned them. But every one of them also carried a message back to the authorities in Tehran: the man you have tried to erase is, right now, being celebrated by the world.' },
      { t: 'line', x: 'They tried to make him invisible. He became one of the most watched filmmakers on earth.' },
      { t: 'divider' },
      { t: 'h', x: 'What the camera does' },
      { t: 'p', x: 'Panahi’s career has become a study in what an artist does when the state orders him to stop. He did not make speeches. He did not wait for permission that was never coming. He kept the camera running, quietly, in kitchens and cars and back rooms, and let the films make the argument on his behalf.' },
      { t: 'p', x: 'That is the discipline underneath the defiance. Not noise, but persistence. A refusal, held steady across years, to accept that the work could be forbidden. The films exist. That, in the end, is the whole point.' },
    ],
    source: {
      label: 'Drawn in part from Variety\u2019s reporting on Jafar Panahi. Read the original',
      url: 'https://variety.com/2026/film/global/jafar-panahi-prison-sentence-iranian-court-1236768803/',
    },
  },
  {
    key: 'amiri',
    subject: 'Mike Amiri',
    kicker: 'FASHION',
    title: 'Mike Amiri Built a Luxury House on Rock and Roll',
    standfirst: 'Mike Amiri dressed musicians before he had a label. That instinct for rock and roll became AMIRI, one of the most successful luxury brands to emerge from Los Angeles.',
    excerpt: 'He made stage clothes for musicians first. That instinct became one of LA\u2019s biggest luxury houses.',
    readMins: 4,
    cover: 'article-amiri-cover',
    hero: 'article-amiri-hero',
    tag: 'FASHION',
    blocks: [
      { t: 'lead', x: 'Before AMIRI showed in Paris, before the celebrities and the runway, Mike Amiri was making one-off pieces by hand for musicians who needed to look a certain way under stage lights.' },
      { t: 'p', x: 'He grew up in Los Angeles, inside its music culture, and that is where the eye was trained. He was not studying fashion in the abstract. He was making clothes for people whose entire job is to be looked at, and learning, piece by piece, what reads from a stage and what falls flat.' },
      { t: 'line', x: 'He learned to design for the moment a guitarist steps into the light, not for a mannequin in a showroom.' },
      { t: 'p', x: 'That apprenticeship, dressing rock musicians one garment at a time, gave him something a design school cannot. He understood the specific glamour of rock and roll from the inside: the wear, the attitude, the sense that a great piece of stage clothing looks like it has already lived a life. He was not borrowing the aesthetic. He had grown up in it.' },
      { t: 'divider' },
      { t: 'h', x: 'Turning a feeling into a house' },
      { t: 'p', x: 'He founded AMIRI in 2014, and the brand carried that DNA without dilution. Distressed denim finished by hand. Rocker silhouettes. An unmistakably Los Angeles sensibility, lifted to the price and the craft of a luxury house. It filled a gap nobody else had quite named.' },
      { t: 'pull', x: 'Nobody else was making rock and roll feel that expensive, and that precise.' },
      { t: 'p', x: 'The distressing that looks careless is the opposite of careless. Each piece is worked by hand to arrive at a specific kind of worn, the kind that takes real skill to fake. That tension, studied craft producing something that looks effortless and lived-in, is the whole trick of the brand, and it is why the clothes command the prices they do.' },
      { t: 'divider' },
      { t: 'h', x: 'Paris, without losing the thread' },
      { t: 'p', x: 'AMIRI grew fast, from a cult favourite into a serious house showing on the Paris schedule, worn by exactly the kind of musicians Amiri had started out dressing. The remarkable part is how little the vision drifted as the business scaled. Growth usually softens a point of view. His only sharpened.' },
      { t: 'quote', x: 'Elvis stays on my moodboard. That feeling never leaves the work.', who: 'Mike Amiri' },
      { t: 'p', x: 'He kept his references close and his instinct fixed. The clothes still look like they belong on a stage. They are just made now with the resources of a global luxury company instead of the hands of one man in Los Angeles. The scale changed. The feeling did not.' },
      { t: 'line', x: 'The kid making stage clothes and the designer showing in Paris are chasing the exact same feeling.' },
      { t: 'p', x: 'That is the achievement, and it is rarer than it sounds: to follow one specific instinct from the very bottom of an industry to the very top, and never once let go of the thing that started it. Most designers lose the thread on the way up. Amiri built the whole house out of refusing to.' },
    ],
    source: {
      label: 'Drawn in part from GQ\u2019s profile of Mike Amiri. Read the original',
      url: 'https://www.gq.com/story/mike-amiri-profile-paris-fashion-week',
    },
  },
  {
    key: 'taherpour',
    subject: 'Saman Taherpour',
    kicker: 'DESIGN',
    title: 'Saman Taherpour and the Discipline of Kiani Concept',
    standfirst: 'The designer behind Kiani Concept works in a spare, exacting style where nothing is decorative and every line has a reason.',
    excerpt: 'A designer working in a spare, exacting style where nothing is decorative and every line earns its place.',
    readMins: 4,
    cover: 'article-taherpour-cover',
    tag: 'PROFILE',
    blocks: [
      { t: 'lead', x: 'Saman Taherpour designs the way a good editor writes: by removing everything that does not need to be there, until what is left feels inevitable.' },
      { t: 'p', x: 'Through his studio, Kiani Concept, he works in a restrained, exacting visual language. The forms are clean, the palette is disciplined, the detailing is quiet. Nothing is added for effect. It is the kind of work that looks simple until you try to do it yourself and realise how much judgement each decision took.' },
      { t: 'line', x: 'Anyone can add. The hard discipline is knowing what to leave out.' },
      { t: 'divider' },
      { t: 'h', x: 'The long way to a clear line' },
      { t: 'p', x: 'Work this spare does not come from nowhere. It comes from years of looking, testing, and discarding, from a designer who kept refining a point of view until it was strong enough to say very little and still say everything. The calm you see in the finished work is the last step of a long process, not the first.' },
      { t: 'p', x: 'Taherpour built Kiani Concept as the vehicle for that vision: a studio with a single, consistent sensibility rather than a portfolio that chases whatever is current. That is a harder path. It means turning down the easy flourish, resisting the trend, and trusting that restraint will read as confidence rather than absence.' },
      { t: 'pull', x: 'A spare object is only as good as its worst line. There is nowhere to hide.' },
      { t: 'img', key: 'article-taherpour-work' },
      { t: 'divider' },
      { t: 'h', x: 'Restraint as the whole method' },
      { t: 'p', x: 'The through line in everything he makes is control. Where a lot of design reaches for more, more texture, more colour, more ornament, Taherpour reaches for less, and trusts proportion and material to carry the result. That is the harder position to hold, because a single weak decision has nowhere to hide in work this clean.' },
      { t: 'p', x: 'It is a sensibility with deep roots in the region he comes from, where geometry and restraint have always done the heavy lifting, where a plain surface and a perfect proportion were understood to be worth more than decoration. But the work itself is contemporary and quietly international. It does not announce where it is from. It simply carries it.' },
      { t: 'line', x: 'The confidence is not in what he puts on the page. It is in what he is willing to leave off it.' },
      { t: 'divider' },
      { t: 'h', x: 'What the work argues' },
      { t: 'p', x: 'What Kiani Concept demonstrates, piece after piece, is that a strong point of view does not need volume. It needs consistency, and the nerve to hold a line when everything around you is getting louder. In a field that rewards the eye-catching, Taherpour bet on the quietly excellent, and made that the entire identity of the studio.' },
      { t: 'p', x: 'The result is design that reads as calm and considered rather than loud, work you keep looking at precisely because it is not trying to grab you. That is the whole vision, and it is a genuinely difficult one to sustain: say less, mean more, and trust the person looking to feel the difference.' },
    ],
    source: {
      label: 'Drawn in part from Kiani Concept. Read more',
      url: 'https://kianiconcept.com/about/',
    },
  },
  {
    key: 'ghalichi',
    subject: 'Lilly Ghalichi',
    kicker: 'BUSINESS',
    title: 'Lilly Ghalichi Turned Lashes Into a Ten Year Brand',
    standfirst: 'A lawyer by training, Lilly Ghalichi built Lilly Lashes into one of the most recognisable names in the beauty accessory market.',
    excerpt: 'A trained lawyer who built one of beauty\u2019s most recognisable lash brands, and kept it for a decade.',
    readMins: 3,
    cover: 'article-ghalichi-cover',
    tag: 'BUSINESS',
    blocks: [
      { t: 'lead', x: 'Lilly Ghalichi qualified as a lawyer before she ever sold a lash. The training turned out to be the point.' },
      { t: 'p', x: 'She founded Lilly Lashes in 2013 and built it into one of the most recognisable brands in its category, a decade and counting in a market where most beauty labels do not survive their third year. The product was false lashes; the achievement was durability.' },
      { t: 'h', x: 'A brand built on visibility' },
      { t: 'p', x: 'Ghalichi understood early how attention converts to sales. She built a strong public profile and used it as the launch platform for the brand, pairing a distinctive, dramatic product with an owner who was herself the clearest advertisement for it. The lashes were designed to be noticed, and so was the marketing.' },
      { t: 'img', key: 'article-ghalichi-product', cap: 'Lilly Lashes: a product designed to be noticed.' },
      { t: 'p', x: 'The legal background shows up in how the company is run. Trademarks, licensing, and the structure of the business were handled with a precision that a lot of founder led beauty brands never manage, which is part of why it lasted.' },
      { t: 'p', x: 'Ten years on, Lilly Lashes is a case study in taking a small, specific product and building something lasting around it, through relentless visibility and disciplined ownership.' },
    ],
    source: {
      label: 'Drawn in part from an interview with Lilly Ghalichi on Lilly Lashes. Read the original',
      url: 'https://lillylashes.com/blogs/news/interview-with-lilly-ghalichi-celebrating-iwd-10-years-of-lilly-lashes',
    },
  },
  {
    key: 'choopan',
    subject: 'Hadi Choopan',
    kicker: 'SPORT',
    title: 'Hadi Choopan Carried the Olympia Home to Iran',
    standfirst: 'From a village near Shiraz to the top of professional bodybuilding, Hadi Choopan became Mr Olympia in 2022 against long odds.',
    excerpt: 'From a village near Shiraz to Mr Olympia, against travel bans, visa fights, and long odds.',
    readMins: 4,
    cover: 'article-choopan-cover',
    tag: 'SPORT',
    blocks: [
      { t: 'lead', x: 'They call Hadi Choopan the Persian Wolf. In 2022 he became Mr Olympia, the highest title in professional bodybuilding, and the first Iranian ever to hold it.' },
      { t: 'p', x: 'He grew up in a village in the Sepidan region near Shiraz, and trained for years in conditions nothing like the resourced, climate-controlled gyms of the men he would one day beat. His talent was obvious early. The obstacles were not about talent at all.' },
      { t: 'line', x: 'The gap he had to close was never about ability. It was about everything around the ability.' },
      { t: 'divider' },
      { t: 'h', x: 'The years he lost' },
      { t: 'p', x: 'For several years, at the very moment his career should have been building, Choopan could not travel to compete. Visa and travel restrictions kept him in Iran while his rivals abroad piled up the international stage experience he was denied. A bodybuilder is judged on stage, in person, and he was being kept off the one place the title is won.' },
      { t: 'pull', x: 'His competitors were gaining years of stage time he was simply not allowed to have.' },
      { t: 'p', x: 'When he finally did compete internationally, he placed near the very top almost immediately. That result said something plainly: the years he had lost had cost him nothing in ability, only in time. He had been that good the whole time. The world just had not been allowed to see it.' },
      { t: 'img', key: 'article-choopan-1' },
      { t: 'divider' },
      { t: 'h', x: 'Winning it all' },
      { t: 'p', x: 'He kept climbing, and in 2022 he took the Olympia title outright. The physique that won is known for a rare combination of size, conditioning, and fine detail, the exact qualities the sport prizes most. But the story around it, the late start on the world stage and the years spent unable to compete, is a large part of why the win landed as hard as it did.' },
      { t: 'line', x: 'He reached the top of his sport years late, and made it look like he had always belonged there.' },
      { t: 'img', key: 'article-choopan-2' },
      { t: 'divider' },
      { t: 'h', x: 'What he did with the title' },
      { t: 'p', x: 'Choopan dedicated his Olympia win, publicly, to the women of Iran, at a moment when doing so carried real weight and real risk. In a sport that rarely reaches beyond its own audience, that single gesture turned a bodybuilding trophy into something people far outside the gym paid attention to.' },
      { t: 'p', x: 'It is the whole shape of his story in one act. A man who was kept off the stage for years, who won anyway, and who used the first moment the world was truly watching to point the attention somewhere other than himself.' },
    ],
    source: {
      label: 'Drawn in part from BarBend\u2019s profile of Hadi Choopan. Read the original',
      url: 'https://barbend.com/hadi-choopan/',
    },
  },
  {
    key: 'zandesh',
    subject: 'Keivan Zandesh',
    kicker: 'BUSINESS  ·  A LIFE',
    title: 'The Man Who Built Sweden\u2019s Candy Empire',
    standfirst: 'Keivan Zandesh runs 4-Gott, among the largest pick and mix candy retailers in western Sweden, out of Gothenburg. He sells sweets by the ton.',
    excerpt: 'He turned Sweden’s love of Saturday sweets into one of Scandinavia’s biggest candy operations.',
    readMins: 3,
    cover: 'article-zandesh-cover',
    tag: 'PROFILE',
    blocks: [
      { t: 'lead', x: 'Keivan Zandesh sells candy by the ton. His company, 4-Gott, runs some of the largest pick and mix operations in western Sweden, out of Gothenburg.' },
      { t: 'p', x: 'He came to Sweden around the time of the Iranian revolution and started with very little. He built the business up over years into an operation known regionally for the scale of its selection: walls of loose candy, bins by the hundred, volumes that most confectionery retailers never attempt.' },
      { t: 'h', x: 'Reading the Swedish market' },
      { t: 'p', x: 'Sweden has an unusually strong candy culture. The tradition of lordagsgodis, Saturday sweets, is a fixed national habit, and loose pick and mix is how most of it is bought. Zandesh built specifically around that demand, competing on range and price at a scale that turned a common product into a serious business.' },
      { t: 'img', key: 'article-zandesh-store', cap: 'A 4-Gott store, where candy is sold loose and by weight.' },
      { t: 'p', x: 'The model is simple and hard to execute: buy well, stock deep, keep prices low, and offer more variety than anyone nearby. Doing that consistently, across a large retail footprint, is what separates a shop from a chain.' },
      { t: 'h', x: 'The operator behind it' },
      { t: 'p', x: 'What the business runs on is operational discipline: supply, logistics, and margins on a product sold cheaply in enormous quantity. Zandesh built and still runs it from Gothenburg, and it stands as one of the more distinctive retail successes in the region.' },
    ],
    source: {
      label: 'Drawn in part from G\u00f6teborgs-Posten\u2019s reporting. Read the original',
      url: 'https://www.gp.se/ekonomi/han-saljer-tonvis-med-godis-till-vastsvenskar.6f3f217f-329b-49bf-a651-2fb7a2de69fc',
    },
  },
  {
    key: 'ansari',
    subject: 'Anousheh Ansari',
    kicker: 'SCIENCE  ·  A LIFE',
    title: 'Anousheh Ansari, the First Iranian in Space',
    standfirst: 'She left Iran as a teenager who did not speak the language, became an engineer and entrepreneur, and then paid her own way to the edge of the world. In 2006 she looked down at Earth from orbit.',
    excerpt: 'He turned Sweden’s love of Saturday sweets into one of the region’s biggest candy operations.',
    readMins: 4,
    cover: 'article-ansari-cover',
    tag: 'SCIENCE',
    blocks: [
      { t: 'lead', x: 'As a child in Iran, Anousheh Ansari would lie outside and stare at the stars, certain she would reach them one day. Almost everyone has that thought once. She is one of the very few who did something about it.' },
      { t: 'p', x: 'She emigrated to the United States as a teenager, arriving without speaking English, and did what a certain kind of person does with a hard beginning. She turned it into fuel. She studied electrical engineering and computer science, and with her husband and brother-in-law built a telecommunications company that they eventually sold for a great deal of money.' },
      { t: 'line', x: 'She arrived without the language, and turned a hard start into the resources to reach orbit.' },
      { t: 'p', x: 'That is the part that gets lost when people hear space tourist. This was not a lark. It was the end of a long climb that began with a teenager in a new country who could not yet speak to the people around her, and who decided that would not be the thing that stopped her.' },
      { t: 'divider' },
      { t: 'h', x: 'The ticket to orbit' },
      { t: 'p', x: 'Most people who make that kind of money buy the usual things. Ansari bought a seat on a Russian Soyuz rocket. In September 2006 she flew to the International Space Station, becoming the first Iranian in space, the first Muslim woman in space, and the world’s first self-funded woman to make the trip.' },
      { t: 'pull', x: 'She did not just buy a ticket to space. Years earlier, she had helped build the road.' },
      { t: 'p', x: 'Because before the flight, her family had put up the prize money for the competition that pushed the first privately built craft past the edge of space, the contest that now carries the Ansari name. She helped make the entire era of private spaceflight possible, and then she went herself. Few people fund the frontier and then cross it.' },
      { t: 'divider' },
      { t: 'h', x: 'What she carried up' },
      { t: 'p', x: 'She took two flags with her to orbit, the American and the Iranian, and she kept a blog from space, writing in plain, moving language about what it felt like to look down at a borderless Earth. For millions of Iranians, and especially Iranian girls, she became proof of something specific: that the ceiling was much higher than they had been told.' },
      { t: 'quote', x: 'From up there, the Earth has no borders. It is one thing, and we are all on it together.', who: 'Anousheh Ansari' },
      { t: 'p', x: 'She has spent the years since as an advocate for science, for entrepreneurship, and for the idea that a girl looking up at the stars from anywhere on Earth might one day look back down at it. She did it first, and she has made a point of saying, loudly, that she does not intend to be the last.' },
      { t: 'line', x: 'A girl who stared at the stars from Tehran looked back down at the whole Earth from space.' },
    ],
    source: {
      label: 'Drawn in part from Space.com\u2019s interview with Anousheh Ansari. Read the original',
      url: 'https://www.space.com/2889-interview-anousheh-ansari-female-space-tourist.html',
    },
  },
  {
    key: 'ferdowsi',
    subject: 'Arash Ferdowsi',
    kicker: 'TECHNOLOGY  ·  A LIFE',
    title: 'Arash Ferdowsi, Who Helped Put Everyone\u2019s Files in the Cloud',
    standfirst: 'The son of Iranian immigrants dropped out of MIT to co found Dropbox, a company that quietly changed how hundreds of millions of people keep their work.',
    excerpt: 'He left MIT one semester short to co found Dropbox. Hundreds of millions of people use it.',
    readMins: 3,
    cover: 'article-ferdowsi-cover',
    tag: 'TECHNOLOGY',
    blocks: [
      { t: 'lead', x: 'There is a good chance your files have lived, at some point, inside something Arash Ferdowsi helped build. That is a strange kind of fame: enormous reach, almost no recognition. He seems to have preferred it that way.' },
      { t: 'p', x: 'The son of Iranian immigrants, Ferdowsi grew up in the American Midwest and went to MIT to study electrical engineering and computer science. He did not finish. In 2007 he dropped out, one semester short, to co found a company with Drew Houston, built around a simple, maddening problem: keeping your files with you, everywhere, without thinking about it.' },
      { t: 'pull', x: 'Enormous reach, almost no recognition. He seems to have preferred it that way.' },
      { t: 'h', x: 'The boring problem everyone had' },
      { t: 'p', x: 'That company was Dropbox. The idea sounds obvious now, which is the highest compliment you can pay a piece of infrastructure. Before it, moving your work between your own machines meant emailing files to yourself, or carrying a USB stick, or simply losing things. Dropbox made the problem disappear so completely that people forgot it had ever existed.' },
      { t: 'p', x: 'As co founder and chief technology officer, Ferdowsi was the engineering conscience of the company through the years when it grew from an idea into something used by hundreds of millions of people and worth billions.' },
      { t: 'h', x: 'The quiet immigrant story' },
      { t: 'p', x: 'His is the version of the immigrant success story that rarely gets the film treatment, because it is built from patience rather than drama. Parents who arrive and work. A child given an education they treat as sacred. A young man who bets a prestigious degree on an unglamorous problem, and turns out to be right.' },
      { t: 'quote', x: 'The best infrastructure is the kind you forget is even there.', who: 'The Dropbox idea' },
      { t: 'p', x: 'Ferdowsi shares a surname with the poet who saved the Persian language a thousand years ago. It is a coincidence, but a fitting one: both men, in their very different centuries, worked on the quiet machinery that lets people keep what matters to them.' },
    ],
    source: {
      label: 'Drawn in part from Operator Atlas\u2019s profile of Arash Ferdowsi. Read the original',
      url: 'https://operatoratlas.com/founders/arash-ferdowsi',
    },
  },
  {
    key: 'cultgaia',
    subject: 'Jasmin Larian',
    kicker: 'DESIGN  ·  A LIFE IN OBJECTS',
    title: 'Jasmin Larian Hekmat Built a Cult From an Ark Bag',
    standfirst: 'Jasmin Larian Hekmat founded Cult Gaia in 2012. Its bamboo Ark bag became one of the most recognisable, and most copied, accessories of its era.',
    excerpt: 'One bamboo bag became the most copied accessory of the decade. Here is the mind behind it.',
    readMins: 3,
    cover: 'article-cultgaia-cover',
    tag: 'PROFILE',
    blocks: [
      { t: 'lead', x: 'The Cult Gaia Ark bag, a structured fan of polished bamboo, became one of the most recognisable accessories of its era, and one of the most widely copied.' },
      { t: 'p', x: 'Jasmin Larian Hekmat founded Cult Gaia in Los Angeles in 2012. She grew up close to the business of consumer products: her family founded MGA Entertainment, the toy company behind Bratz, so the mechanics of how an object catches on were familiar to her early.' },
      { t: 'h', x: 'A sculptural approach to accessories' },
      { t: 'p', x: 'From the start the brand treated accessories as objects first. The early pieces favoured natural materials and strong, sculptural silhouettes, designed to read as much as a shape as a product. The Ark bag was the clearest expression of that: instantly identifiable, and unlike what most competitors were making.' },
      { t: 'img', key: 'article-cultgaia-1', cap: 'Cult Gaia treats the accessory as a sculptural object first.' },
      { t: 'p', x: 'A single breakout product is difficult to build on; many brands never get past their first hit. Larian Hekmat used the Ark as a base rather than a peak, expanding Cult Gaia into ready to wear, footwear, and a full collection with a consistent design language.' },
      { t: 'img', key: 'article-cultgaia-2', cap: 'The brand expanded from one object into a full ready to wear line.' },
      { t: 'h', x: 'Running the brand' },
      { t: 'p', x: 'She has kept creative control while scaling the company through wholesale and direct to consumer, in a crowded market where recognisability is the hardest thing to hold. Cult Gaia’s durability past its viral moment is the real measure of how it was built.' },
    ],
    source: {
      label: 'Drawn in part from Glamour\u2019s interview with Jasmin Larian Hekmat. Read the original',
      url: 'https://www.glamourmagazine.co.uk/article/cult-gaia-jasmin-larian-interview',
    },
  },
  {
    key: 'gisou',
    subject: 'Negin Mirsalehi',
    kicker: 'BEAUTY  ·  A FAMILY INHERITANCE',
    title: 'Negin Mirsalehi Turned Her Family\u2019s Bees Into a Beauty Empire',
    standfirst: 'Negin Mirsalehi co founded Gisou in 2015, built around her family’s beekeeping and a honey based hair oil. She launched it to an audience of millions she had already built online.',
    excerpt: 'Six generations of beekeeping, a family honey recipe, and one of beauty’s fastest rises.',
    readMins: 3,
    cover: 'article-gisou-cover',
    hero: 'article-gisou-portrait',
    tag: 'PROFILE',
    blocks: [
      { t: 'lead', x: 'Gisou is built around one ingredient: honey, from a family bee garden in the Netherlands that has been kept for six generations.' },
      { t: 'p', x: 'Negin Mirsalehi co founded the brand in 2015. Her father is a beekeeper, and the honey based hair oil at the centre of the line comes from a family recipe. The bee garden gives the brand a genuine, verifiable source, which is rare in beauty.' },
      { t: 'h', x: 'Audience first, then product' },
      { t: 'p', x: 'Mirsalehi built a large online following before launching anything, becoming one of the earlier creators to convert an audience into a company. By the time Gisou existed, there was already a built in base of people who trusted her recommendations. That distribution advantage is a large part of why the brand scaled quickly.' },
      { t: 'img', key: 'article-gisou-garden', cap: 'The Mirsalehi bee garden, the brand honey source.' },
      { t: 'p', x: 'The name is deliberate: gisou means tresses in Persian, which is what the products are made for. The brand leans on a single, defensible origin story rather than an invented one, and pairs it with strong direct to consumer marketing.' },
      { t: 'h', x: 'Why it worked' },
      { t: 'p', x: 'Gisou grew into one of the most talked about brands in beauty on the strength of two things that are hard to fake together: a real, differentiated hero ingredient, and an owned audience to launch it to. Most brands have one or the other. Mirsalehi built the audience first, then had a product with an actual source to sell it.' },
    ],
    source: {
      label: 'Drawn in part from Gisou\u2019s own heritage story. Read the original',
      url: 'https://gisou.com/blogs/blog/gisou-heritage-story',
    },
  },
  _ebi_obj,
  _omid_obj,
];

export function articleByKey(k?: string) {
  return ARTICLES.find((a) => a.key === k);
}

// The order the Articles page shows them in. Old and new deliberately mixed.
// The first key is the hero. Change this list to re-curate the page.
export const ARTICLE_ORDER: string[] = [
  'googoosh',   // hero
  'khalili',
  'amiri',
  'panahi',
  'gisou',
  'rassi',
  'ansari',
  'zadeh',
  'cultgaia',
  'choopan',
  'ghalichi',
  'zandesh',
  'taherpour',
  'ferdowsi', 'ebi', 'omid'];

export function orderedArticles() {
  const byKey = Object.fromEntries(ARTICLES.map((a) => [a.key, a]));
  const seen = new Set<string>();
  const out = [] as typeof ARTICLES;
  for (const k of ARTICLE_ORDER) { if (byKey[k]) { out.push(byKey[k]); seen.add(k); } }
  for (const a of ARTICLES) if (!seen.has(a.key)) out.push(a); // any not listed, appended
  return out;
}



// A different article each day for the home 'new this week' slot.
export function articleOfDay(d = new Date()) {
  const all = orderedArticles();
  if (all.length === 0) return undefined;
  const day = Math.floor(d.getTime() / 86400000);
  return all[day % all.length];
}
