// A memorial, not a list. Each name here is documented by human rights
// organisations, by name and by date. There are thousands more.
//
// Positions are fractions of the illustration box, the same model the
// province map uses.

export type Remembered = {
  key: string;
  name: string;
  persian?: string;
  age?: string;
  when: string;
  where: string;
  what: string;
  whatFa?: string;
  whenFa?: string;
  whereFa?: string;
  ageFa?: string;
  image: string;   // admin-uploadable slot
  x: number;
  y: number;
};

export const REMEMBERED: Remembered[] = [
  {
    key: 'diana',
    name: 'Diana Nasseri',
    persian: 'دیانا ناصری',
    age: '19',
    ageFa: '۱۹',
    when: 'January 2026',
    whenFa: 'دی ۱۴۰۴',
    where: 'Gorgan',
    whereFa: 'گرگان',
    what: 'Nineteen, and known online to a large following for ordinary things. She was killed by security forces during the crackdown in Gorgan. Her family were pressured over what could be said about how she died.',
    whatFa: 'نوزده ساله بود و در فضای مجازی دنبال‌کنندگان زیادی داشت، برای چیزهای معمولی. در جریان سرکوب گرگان به دست نیروهای امنیتی کشته شد. بر خانواده‌اش فشار آوردند که دربارهٔ چگونگی مرگش چه بگویند.',
    image: 'mem-diana',
    x: 0.66, y: 0.58,
  },
  {
    key: 'ghazaleh',
    name: 'Ghazaleh Chalabi',
    persian: 'غزاله چلابی',
    age: '33',
    ageFa: '۳۳',
    when: 'September 2022',
    whenFa: 'شهریور ۱۴۰۱',
    where: 'Amol',
    whereFa: 'آمل',
    what: 'She was filming the protest when she was shot. The footage keeps running for a few seconds after she falls, and her own voice can be heard on it saying, do not be afraid, do not be afraid.',
    whatFa: 'داشت از اعتراض فیلم می‌گرفت که هدف گلوله قرار گرفت. فیلم چند ثانیه پس از افتادنش هم ادامه دارد، و صدای خودش روی آن شنیده می‌شود که می‌گوید نترسید، نترسید.',
    image: 'mem-ghazaleh',
    x: 0.34, y: 0.74,
  },
  {
    key: 'siavash',
    name: 'Siavash Mahmoudi',
    persian: 'سیاوش محمودی',
    age: '18',
    ageFa: '۱۸',
    when: 'September 2022',
    whenFa: 'شهریور ۱۴۰۱',
    where: 'Tehran',
    whereFa: 'تهران',
    what: 'Eighteen, shot in the street during the protests in Tehran. His family were told to bury him quietly and quickly, as many families were.',
    whatFa: 'هجده ساله بود و در خیابان، در جریان اعتراض‌های تهران، هدف گلوله قرار گرفت. به خانواده‌اش گفتند بی‌سروصدا و زود به خاکش بسپارند، همان‌طور که به خیلی از خانواده‌ها گفتند.',
    image: 'mem-siavash',
    x: 0.44, y: 0.86,
  },
  {
    key: 'neda',
    name: 'Neda Agha-Soltan',
    persian: 'ندا آقاسلطان',
    age: '26',
    ageFa: '۲۶',
    when: 'June 2009',
    whenFa: 'شهریور ۱۳۸۸',
    where: 'Tehran',
    whereFa: 'تهران',
    what: 'A philosophy student who had stepped out of a car in the heat during the Green Movement protests. She was shot in the chest and died in the street. Someone filmed it, and the footage travelled around the world within hours. She had not been chanting.',
    whatFa: 'دانشجوی فلسفه بود که در گرمای تیرماه از ماشین پیاده شده بود، در جریان اعتراض‌های جنبش سبز. از ناحیهٔ سینه هدف گلوله قرار گرفت و در خیابان جان داد. کسی فیلم گرفت، و ظرف چند ساعت در سراسر جهان پخش شد. شعار نمی‌داد.',
    image: 'mem-neda',
    x: 0.63, y: 0.34,
  },
  {
    key: 'mahsa',
    name: 'Mahsa Jina Amini',
    persian: 'مهسا ژینا امینی',
    age: '22',
    ageFa: '۲۲',
    when: 'September 2022',
    whenFa: 'شهریور ۱۴۰۱',
    where: 'Tehran, from Saqqez',
    whereFa: 'تهران، اهل سقز',
    what: 'A Kurdish woman visiting Tehran with her family, detained by the morality police over how she was wearing her hijab. She collapsed in custody and died three days later. Her family said she had been beaten. Her funeral became the first protest of what followed.',
    whatFa: 'دختری کرد که با خانواده‌اش به تهران آمده بود و گشت ارشاد به بهانهٔ نحوهٔ پوشیدن حجابش بازداشتش کرد. در بازداشت از حال رفت و سه روز بعد درگذشت. خانواده‌اش گفتند کتک خورده است. خاکسپاری‌اش به نخستین اعتراض بدل شد.',
    image: 'mem-mahsa',
    x: 0.72, y: 0.44,
  },
  {
    key: 'kian',
    name: 'Kian Pirfalak',
    persian: 'کیان پیرفلک',
    age: '9',
    ageFa: '۹',
    when: 'November 2022',
    whenFa: 'آبان ۱۴۰۱',
    where: 'Izeh',
    whereFa: 'ایذه',
    what: 'Nine years old, in the back of his family car when it was fired on. His mother spoke at his funeral and said plainly who had shot him, in front of everyone. He had recorded a video weeks earlier explaining a boat he was building.',
    whatFa: 'نه ساله بود، در صندلی عقب ماشین خانواده وقتی به آن شلیک شد. مادرش بر سر خاکش ایستاد و در برابر همه، صریح گفت چه کسی او را کشته است. چند هفته پیش‌تر ویدئویی ضبط کرده بود و در آن قایقی را که می‌ساخت توضیح می‌داد.',
    image: 'mem-kian',
    x: 0.78, y: 0.55,
  },
  {
    key: 'nika',
    name: 'Nika Shakarami',
    persian: 'نیکا شاکرمی',
    age: '16',
    ageFa: '۱۶',
    when: 'September 2022',
    whenFa: 'شهریور ۱۴۰۱',
    where: 'Tehran',
    whereFa: 'تهران',
    what: 'Sixteen, at a protest in Tehran. She told a friend she was being followed and was not heard from again. Her body was returned to her family ten days later, and they were pressured over what they could say about it.',
    whatFa: 'شانزده ساله بود، در اعتراضی در تهران. به دوستش گفت که تعقیبش می‌کنند، و دیگر خبری از او نشد. ده روز بعد پیکرش را به خانواده‌اش تحویل دادند، و بر آنها فشار آوردند که دربارهٔ چگونگی مرگش چه بگویند.',
    image: 'mem-nika',
    x: 0.58, y: 0.5,
  },
  {
    key: 'sarina',
    name: 'Sarina Esmailzadeh',
    persian: 'سارینا اسماعیل‌زاده',
    age: '16',
    ageFa: '۱۶',
    when: 'September 2022',
    whenFa: 'شهریور ۱۴۰۱',
    where: 'Karaj',
    whereFa: 'کرج',
    what: 'Sixteen, and a video blogger who posted about ordinary teenage things and about the life she hoped for. She was killed during protests in Karaj. The authorities said she had jumped from a roof; her family did not accept it.',
    whatFa: 'شانزده ساله بود و ویدئوبلاگر؛ دربارهٔ چیزهای معمولی نوجوانی و دربارهٔ زندگی‌ای که آرزویش را داشت ویدئو می‌گذاشت. در جریان اعتراض‌های کرج کشته شد. مقام‌ها گفتند از پشت‌بام پریده است؛ خانواده‌اش نپذیرفتند.',
    image: 'mem-sarina',
    x: 0.84, y: 0.53,
  },
  {
    key: 'hadis',
    name: 'Hadis Najafi',
    persian: 'حدیث نجفی',
    age: '22',
    ageFa: '۲۲',
    when: 'September 2022',
    whenFa: 'شهریور ۱۴۰۱',
    where: 'Karaj',
    whereFa: 'کرج',
    what: 'Filmed tying up her hair before walking towards a protest line. She was shot several times and died. The clip of her tying her hair became one of the images of that autumn.',
    whatFa: 'فیلمی از او هست که موهایش را می‌بندد و بعد به سمت صف اعتراض راه می‌افتد. چند گلوله خورد و جان باخت. همان تصویرِ بستن مو، به یکی از تصویرهای آن پاییز بدل شد.',
    image: 'mem-hadis',
    x: 0.52, y: 0.42,
  },
  {
    key: 'khodanoor',
    name: 'Khodanoor Lajaei',
    persian: 'خدانور لجه‌ای',
    age: '27',
    ageFa: '۲۷',
    when: 'September 2022',
    whenFa: 'مهر ۱۴۰۱',
    where: 'Zahedan',
    whereFa: 'زاهدان',
    what: 'A Baluch man killed on the day known as Bloody Friday in Zahedan, when around a hundred people were shot. A photograph taken earlier, showing him chained to a flagpole with water left out of reach, had already circulated widely.',
    whatFa: 'مرد بلوچی که در روزی کشته شد که به جمعهٔ خونین زاهدان معروف شد؛ روزی که حدود صد نفر هدف گلوله قرار گرفتند. عکسی که پیش‌تر از او گرفته شده بود و او را در حالی نشان می‌داد که به میلهٔ پرچم بسته شده و آب را بیرون از دسترسش گذاشته‌اند، از قبل دست به دست می‌گشت.',
    image: 'mem-khodanoor',
    x: 0.4, y: 0.66,
  },
  {
    key: 'mohsen',
    name: 'Mohsen Shekari',
    persian: 'محسن شکاری',
    age: '23',
    ageFa: '۲۳',
    when: 'December 2022',
    whenFa: 'آذر ۱۴۰۱',
    where: 'Tehran',
    whereFa: 'تهران',
    what: 'A café worker, the first person executed in connection with the 2022 protests. He was convicted of blocking a street and wounding a member of the Basij, after a trial that lasted a matter of days and a confession his family said was extracted under torture.',
    whatFa: 'کارگر یک کافه بود، و نخستین کسی که در ارتباط با اعتراض‌های ۱۴۰۱ اعدام شد. به اتهام بستن یک خیابان و مجروح کردن یک بسیجی محکوم شد، پس از محاکمه‌ای که چند روز بیشتر طول نکشید و اعترافی که خانواده‌اش گفتند زیر شکنجه گرفته شده است.',
    image: 'mem-mohsen',
    x: 0.46, y: 0.58,
  },
  {
    key: 'majidreza',
    name: 'Majidreza Rahnavard',
    persian: 'مجیدرضا رهنورد',
    age: '23',
    ageFa: '۲۳',
    when: 'December 2022',
    whenFa: 'آذر ۱۴۰۱',
    where: 'Mashhad',
    whereFa: 'مشهد',
    what: 'Publicly hanged from a crane twenty-three days after his arrest. He asked that no one read the Quran or mourn at his grave, and that people celebrate instead.',
    whatFa: 'بیست و سه روز پس از بازداشتش، در ملأ عام و از جرثقیل به دار آویخته شد. خواسته بود کسی بر سر خاکش قرآن نخواند و عزاداری نکند، و به جایش جشن بگیرند.',
    image: 'mem-majidreza',
    x: 0.83, y: 0.61,
  },
  {
    key: 'hatami',
    name: 'Amirhossein Hatami',
    persian: 'امیرحسین حاتمی',
    age: '18',
    ageFa: '۱۸',
    when: 'January to April 2026',
    whenFa: 'دی ۱۴۰۴ تا فروردین ۱۴۰۵',
    where: 'Tehran',
    whereFa: 'تهران',
    what: 'Eighteen years old, arrested on 8 January 2026. He could not afford a lawyer of his own and was given one by the court. A confession was broadcast on state television ten days after his arrest. He was sentenced to death for enmity against God and executed eighty-four days after he was taken.',
    whatFa: 'هجده ساله بود و در ۱۸ دی ۱۴۰۴ بازداشت شد. توان گرفتن وکیل خودش را نداشت و دادگاه برایش وکیل تعیین کرد. ده روز پس از بازداشتش، اعترافی از او از تلویزیون پخش شد. به اتهام محاربه به اعدام محکوم و هشتاد و چهار روز پس از بازداشتش اعدام شد.',
    image: 'mem-hatami',
    x: 0.7, y: 0.83,
  },
  {
    key: 'isfahan',
    name: 'Amirhossein Safari and Abolfazl Sepahi',
    persian: 'امیرحسین صفری و ابوالفضل سپاهی',
    age: 'both in their twenties',
    ageFa: 'هر دو در دههٔ بیست زندگی',
    when: 'July 2026',
    whenFa: 'مرداد ۱۴۰۵',
    where: 'Isfahan',
    whereFa: 'اصفهان',
    what: 'Two of twelve young men sentenced to death over the protests in Alikhani Square on 8 January. They were hanged in public before dawn. A crowd gathered through the night to try to stop it and was cleared by security forces. Ten others from the same case are still under sentence.',
    whatFa: 'دو تن از دوازده جوانی که به خاطر اعتراض‌های میدان علیخانی در ۱۸ دی به اعدام محکوم شدند. پیش از سپیده‌دم و در ملأ عام به دار آویخته شدند. جمعیتی تمام شب جمع شده بود تا جلویش را بگیرد و نیروهای امنیتی پراکنده‌شان کردند. ده نفر دیگر از همین پرونده هنوز زیر حکم اعدام‌اند.',
    image: 'mem-isfahan',
    x: 0.82, y: 0.9,
  },
];
