// Per-letter handwriting guidance for the Writing workbook.

export type WritingGuide = { strokes: string; dots: string; baseline?: string; tip: string };

export const WRITING: Record<string, WritingGuide> = {
  'آ': { strokes: '2', dots: 'No dots — a madda (~) sits on top', tip: 'A tall vertical stroke drawn top to bottom, crowned with a wavy madda.' },
  'ا': { strokes: '1', dots: 'No dots', tip: 'A single straight vertical stroke, drawn top to bottom. Never joins to the left.' },
  'ب': { strokes: '2', dots: 'One dot below', tip: 'A shallow bowl along the line, then one dot beneath the centre.' },
  'پ': { strokes: '4', dots: 'Three dots below', tip: 'The same bowl as be, with three dots grouped beneath.' },
  'ت': { strokes: '3', dots: 'Two dots above', tip: 'The bowl shape, then two dots side by side on top.' },
  'ث': { strokes: '4', dots: 'Three dots above', tip: 'The bowl shape, then three dots grouped on top.' },
  'ج': { strokes: '2', dots: 'One dot below', baseline: 'Its bowl dips below the line', tip: 'A curved hook that swings below the baseline, one dot inside.' },
  'چ': { strokes: '4', dots: 'Three dots below', baseline: 'Dips below the line', tip: 'Like jim, with three dots below the bowl.' },
  'ح': { strokes: '1', dots: 'No dots', baseline: 'Dips below the line', tip: 'A single flowing stroke that loops below the line.' },
  'خ': { strokes: '2', dots: 'One dot above', baseline: 'Dips below the line', tip: 'Like he, with one dot placed above.' },
  'د': { strokes: '1', dots: 'No dots', tip: 'A short bent stroke sitting on the line. Never joins to the left.' },
  'ذ': { strokes: '2', dots: 'One dot above', tip: 'Like dâl, with one dot on top. Never joins to the left.' },
  'ر': { strokes: '1', dots: 'No dots', baseline: 'Tail drops below the line', tip: 'A curved stroke sweeping below the baseline. Never joins to the left.' },
  'ز': { strokes: '2', dots: 'One dot above', baseline: 'Drops below the line', tip: 'Like re, with one dot above.' },
  'ژ': { strokes: '4', dots: 'Three dots above', baseline: 'Drops below the line', tip: 'Like re, with three dots above.' },
  'س': { strokes: '1', dots: 'No dots', baseline: 'Ends in a bowl below the line', tip: 'Three small teeth, then a bowl that dips below the line.' },
  'ش': { strokes: '4', dots: 'Three dots above', baseline: 'Ends below the line', tip: 'Like sin, with three dots above the teeth.' },
  'ص': { strokes: '1', dots: 'No dots', baseline: 'Ends below the line', tip: 'A rounded loop, then a bowl dipping below.' },
  'ض': { strokes: '2', dots: 'One dot above', baseline: 'Ends below the line', tip: 'Like sâd, with one dot above the loop.' },
  'ط': { strokes: '2', dots: 'No dots', tip: 'A flat loop on the line with an upright vertical stroke.' },
  'ظ': { strokes: '3', dots: 'One dot above', tip: 'Like tâ, with one dot above.' },
  'ع': { strokes: '1', dots: 'No dots', baseline: 'Dips below the line', tip: 'An open hook; its shape changes a lot by position.' },
  'غ': { strokes: '2', dots: 'One dot above', baseline: 'Dips below the line', tip: 'Like eyn, with one dot above.' },
  'ف': { strokes: '2', dots: 'One dot above', tip: 'A small round head on the line, one dot above.' },
  'ق': { strokes: '3', dots: 'Two dots above', baseline: 'Bowl dips below the line', tip: 'A round head with a bowl below, two dots above.' },
  'ک': { strokes: '2', dots: 'No dots', tip: 'A tall stroke with a small inner mark — the Persian kâf.' },
  'گ': { strokes: '3', dots: 'No dots', tip: 'Like kâf, with a second short line on top — the Persian gâf.' },
  'ل': { strokes: '1', dots: 'No dots', baseline: 'Curves into a bowl below the line', tip: 'A tall stroke that sweeps into a bowl below the line.' },
  'م': { strokes: '1', dots: 'No dots', baseline: 'Tail drops below', tip: 'A small round head on the line with a tail dropping below.' },
  'ن': { strokes: '2', dots: 'One dot above', baseline: 'Deep bowl below the line', tip: 'A deep round bowl below the line, one dot above the centre.' },
  'و': { strokes: '1', dots: 'No dots', baseline: 'Tail sits below the line', tip: 'A round head with a tail. Never joins to the left.' },
  'ه': { strokes: '1', dots: 'No dots', tip: 'A looping shape that changes the most across the four forms.' },
  'ی': { strokes: '2–3', dots: 'Two dots below (initial & medial forms)', baseline: 'Wide bowl below the line', tip: 'A wide bowl sweeping below the line; the final form is dotless in Persian.' },
  'ء': { strokes: '1', dots: 'A small sign, not a full letter', tip: 'A tiny hook (hamze) marking a glottal catch.' },
};
